/*8*/
CREATE VIEW bigger_battles
AS
 SELECT BATTLE
 FROM OUTCOMES JOIN SHIPS ON SHIP = NAME 
 JOIN CLASSES ON SHIPS.CLASS = CLASSES.CLASS
 WHERE BATTLE NOT LIKE 'Guadalcanal'
 GROUP BY BATTLE
 HAVING COUNT(SHIP) >= ALL(SELECT COUNT(SHIP)
						 FROM OUTCOMES 
						 JOIN SHIPS ON SHIP = NAME
						 WHERE BATTLE = 'Guadalcanal')
AND COUNT(COUNTRY) >= ALL(SELECT COUNT(COUNTRY)
						FROM OUTCOMES 
						JOIN SHIPS ON SHIP = NAME JOIN CLASSES ON SHIPS.CLASS = CLASSES.CLASS
						WHERE BATTLE = 'Guadalcanal')
/*9*/
DELETE FROM OUTCOMES
WHERE SHIP IN(SELECT SHIP
		 FROM OUTCOMES
		 GROUP BY BATTLE,SHIP
		 HAVING COUNT(SHIP) = 1);

/*10*/
INSERT INTO OUTCOMES VALUES 
('Missouri','Surigao Strait', 'sunk'),      
('Missouri','North Cape', 'sunk'),      
('Missouri','North Atlantic', 'ok'); 

DELETE FROM OUTCOMES
WHERE SHIP IN(SELECT SHIP
	  FROM OUTCOMES 
	  JOIN BATTLES ON BATTLE = NAME
	  WHERE RESULT = 'sunk'
	  GROUP BY SHIP
	  HAVING COUNT(DATE) >= 2);

/*11*/
CREATE VIEW battles_countries
AS
 SELECT DISTINCT BATTLE,COUNTRY
 FROM OUTCOMES 
 JOIN SHIPS ON SHIP = NAME JOIN CLASSES ON SHIPS.CLASS = CLASSES.CLASS;

SELECT DISTINCT BATTLE
FROM battles_countries
WHERE BATTLE NOT LIKE 'Guadalcanal'
AND COUNTRY IN(SELECT COUNTRY
                 FROM battles_countries
				 WHERE BATTLE = 'Guadalcanal');

/*12*/
SELECT COUNTRY, COUNT(BATTLE)
FROM CLASSES 
FULL JOIN SHIPS ON CLASSES.CLASS = SHIPS.CLASS 
FULL JOIN OUTCOMES ON SHIP = NAME
GROUP BY COUNTRY;