/*6*/
CREATE VIEW RichExec
AS
 SELECT NAME, ADDRESS, CERT#, NETWORTH
 FROM MOVIEEXEC
 WHERE NETWORTH >= 10000000;

 /*7*/
 CREATE VIEW Executivestar
 AS
  SELECT MOVIESTAR.NAME, MOVIESTAR.ADDRESS, GENDER,BIRTHDATE, CERT#, NETWORTH
  FROM MOVIESTAR JOIN MOVIEEXEC ON MOVIESTAR.NAME = MOVIEEXEC.NAME;

/*8*/
 SELECT RichExec.NAME
 FROM RichExec JOIN STUDIO ON CERT# = PRESC#;

/*9*/
SELECT NAME
 FROM Executivestar
 WHERE GENDER = 'F';
 
 /*10*/
 SELECT NAME
 FROM Executivestar
 WHERE NETWORTH>50000000;
 
 /*11*/
 DROP VIEW RichExec;
 
 DROP VIEW Executivestar;