/*1*/
SELECT m.NAME, mov.TITLE
FROM MOVIEEXEC m JOIN MOVIE mov
ON  m.CERT#=mov.PRODUCERC#
WHERE mov.PRODUCERC#  in (SELECT m3.PRODUCERC#
                              FROM MOVIE m3
							  WHERE m3.TITLE='Star Wars')

/*2*/
SELECT DISTINCT m.NAME
FROM MOVIE mov JOIN STARSIN s
ON  mov.TITLE=s.MOVIETITLE AND mov.YEAR=S.MOVIEYEAR 
JOIN MOVIEEXEC m 
ON m.CERT#=mov.PRODUCERC#
WHERE s.STARNAME ='Harrison Ford'

/*3*/
SELECT DISTINCT s.NAME, st.STARNAME
FROM STUDIO s JOIN MOVIE mov
ON s.NAME = mov.STUDIONAME
JOIN STARSIN st
ON mov.TITLE = st.MOVIETITLE AND mov.YEAR=st.MOVIEYEAR
ORDER BY s.NAME

/*4*/
SELECT st.STARNAME, m.NETWORTH, mov.TITLE
FROM MOVIE mov JOIN STARSIN st
ON mov.YEAR=st.MOVIEYEAR AND mov.TITLE=st.MOVIETITLE
JOIN MOVIEEXEC m
ON mov.PRODUCERC#=m.CERT#
WHERE m.NETWORTH >= ALL (SELECT NETWORTH FROM MOVIEEXEC)

/*5*/
SELECT m.NAME, s.MOVIETITLE
FROM MOVIESTAR m LEFT JOIN STARSIN s
ON m.NAME=s.STARNAME
WHERE s.MOVIETITLE IS NULL