/*1*/
SELECT *
FROM SHIPS s JOIN CLASSES c
ON s.CLASS = c.CLASS
WHERE c.CLASS IS NOT NULL

/*2*/
SELECT *
FROM SHIPS s RIGHT JOIN CLASSES c
ON s.CLASS = c.CLASS
UNION
SELECT *
FROM SHIPS sh JOIN CLASSES cl 
ON sh.CLASS = cl.CLASS
WHERE sh.NAME IS NULL AND cl.CLASS IN (SELECT NAME FROM SHIPS)
ORDER BY NAME

/*3*/
SELECT c.COUNTRY, s.NAME
FROM SHIPS s JOIN CLASSES c
ON s.CLASS = c.CLASS
LEFT JOIN OUTCOMES o 
ON s.NAME = o.SHIP
WHERE o.BATTLE IS NULL
ORDER BY c.COUNTRY

/*4*/
SELECT s.NAME AS 'Ship Name'
FROM SHIPS s JOIN CLASSES c
ON s.CLASS = c.CLASS
WHERE c.NUMGUNS >= 7 AND s.LAUNCHED = 1916

/*5*/
SELECT o.SHIP, b.NAME, b.DATE
FROM OUTCOMES o JOIN BATTLES b
ON o.BATTLE = b.NAME
WHERE o.RESULT = 'sunk'
ORDER BY b.NAME

/*6*/
SELECT s.NAME, c.DISPLACEMENT, s.LAUNCHED
FROM SHIPS s JOIN CLASSES c
ON s.CLASS = c.CLASS
WHERE s.NAME = c.CLASS

/*7*/
SELECT *
FROM CLASSES c LEFT JOIN SHIPS s 
ON c.CLASS = s.CLASS 
WHERE s.LAUNCHED IS NULL

/*8*/
SELECT s.NAME, c.DISPLACEMENT, c.NUMGUNS, o.RESULT
FROM SHIPS s JOIN CLASSES c
ON s.CLASS = c.CLASS
LEFT JOIN OUTCOMES o 
ON s.NAME = o.SHIP
WHERE o.BATTLE = 'North Atlantic'