/*1*/
SELECT COUNT(CLASS) AS numberOfClasses
FROM CLASSES	
WHERE TYPE = 'bb'

/*2*/
SELECT CLASS, AVG(NUMGUNS) AS averageNumGuns
FROM CLASSES
WHERE TYPE = 'bb'
GROUP BY CLASS

/*3*/
SELECT AVG(NUMGUNS) AS averageNumGuns
FROM CLASSES
WHERE TYPE = 'bb'

/*4*/
SELECT c.CLASS, MIN(s.LAUNCHED) AS minYear, MAX(s.LAUNCHED) AS maxYear
FROM CLASSES c JOIN SHIPS s
ON c.CLASS = s.CLASS
WHERE c.TYPE = 'bb'
GROUP BY c.CLASS

/*5*/
SELECT s.CLASS, COUNT(o.RESULT) AS numberOfSunkShips
FROM SHIPS s JOIN OUTCOMES o
ON s.NAME = o.SHIP
WHERE o.RESULT = 'sunk'
GROUP BY s.CLASS

/*6*/
SELECT s.CLASS
FROM SHIPS s JOIN OUTCOMES o
ON s.NAME = o.SHIP
GROUP BY s.CLASS
HAVING COUNT(o.SHIP) >= 2
INTERSECT
SELECT sh.CLASS
FROM SHIPS sh JOIN OUTCOMES ou
ON sh.NAME = ou.SHIP
WHERE ou.RESULT = 'sunk'

/*7*/
SELECT COUNTRY, CONVERT(decimal(4,2), AVG(BORE)) AS averageBore
FROM CLASSES c JOIN SHIPS s
ON c.CLASS = s.CLASS
GROUP BY c.COUNTRY