/*1*/
SELECT DISTINCT s.NAME
FROM SHIPS s JOIN OUTCOMES o
ON s.NAME = o.SHIP
WHERE s.NAME LIKE 'C%' OR  s.NAME LIKE 'K%'
GROUP BY s.NAME
HAVING COUNT(o.BATTLE) >= 1

/*2*/
 SELECT s.NAME, c.COUNTRY
 FROM SHIPS s JOIN CLASSES c ON s.CLASS = c.CLASS 
 WHERE s.name NOT IN  (SELECT SHIP FROM OUTCOMES WHERE RESULT = 'sunk') 

/*3*/
SELECT c.COUNTRY, COUNT(o.RESULT) AS numberOfSunkShips
 FROM SHIPS s RIGHT JOIN CLASSES c ON s.CLASS = c.CLASS  LEFT
 JOIN OUTCOMES o ON s.NAME = O.SHIP
 WHERE o.RESULT = 'sunk' OR o.BATTLE IS NULL OR s.NAME IS NULL /*???*/
 GROUP BY c.COUNTRY

/*4*/
SELECT o.BATTLE
FROM OUTCOMES o
GROUP BY o.BATTLE
HAVING COUNT(o.SHIP) > (SELECT COUNT(ou.SHIP) FROM OUTCOMES ou WHERE ou.BATTLE = 'Guadalcanal')

/*5*/
SELECT o.BATTLE
FROM OUTCOMES o
GROUP BY o.BATTLE
HAVING COUNT(o.SHIP) > (SELECT COUNT(ou.SHIP) FROM OUTCOMES ou WHERE ou.BATTLE = 'Surigao Strait')

/*6*/
SELECT s.NAME, c.DISPLACEMENT, c.NUMGUNS
FROM CLASSES c JOIN SHIPS s
ON c.CLASS = s.CLASS
WHERE c.DISPLACEMENT = (SELECT MIN(DISPLACEMENT) FROM CLASSES WHERE NUMGUNS >= (SELECT MIN(NUMGUNS) FROM CLASSES))
	 
/*7*/
SELECT COUNT(o.SHIP) AS numberOfShips
FROM OUTCOMES o JOIN BATTLES b
ON o.BATTLE = b.NAME
WHERE o.RESULT = 'damaged' AND o.SHIP IN ( SELECT SHIP FROM OUTCOMES WHERE RESULT = 'ok')

/*8*/
 SELECT o1.ship AS shipName
 FROM OUTCOMES o1, OUTCOMES o2, BATTLES b1, BATTLES b2 
 WHERE o1.SHIP = o2.SHIP AND                
 o1.BATTLE = b1.NAME AND                
 o2.BATTLE = b2.NAME AND               
 o1.RESULT = 'damaged' AND               
 o2.RESULT = 'ok' AND               
 b1.DATE < b2.DATE AND              
 (SELECT COUNT(ship)               
 FROM OUTCOMES                
 WHERE BATTLE = o1.BATTLE) < (SELECT COUNT(ship)                     
 FROM OUTCOMES                      
 WHERE BATTLE = o2.BATTLE)