/*1*/
SELECT m.NAME
FROM MOVIESTAR m
WHERE NAME IN (SELECT NAME FROM MOVIEEXEC WHERE NETWORTH >= 10000000 AND m.GENDER = 'F')

/*2*/
SELECT m.NAME
FROM MOVIESTAR m
WHERE NAME NOT IN (SELECT NAME FROM MOVIEEXEC)

/*3*/
SELECT m.TITLE
FROM MOVIE m
WHERE m.LENGTH > (SELECT LENGTH FROM MOVIE WHERE TITLE = 'Star Wars')

/*4*/
SELECT m.TITLE, c.NAME
FROM MOVIE m JOIN MOVIEEXEC c
ON m.PRODUCERC# = c.CERT#
WHERE c.NETWORTH > (SELECT NETWORTH FROM MOVIEEXEC WHERE NAME = 'Merv Griffin')
