/*1*/
SELECT maker
FROM product
WHERE model IN (SELECT model  FROM pc WHERE speed > 500)

/*2*/
SELECT code, model, price
FROM printer
WHERE price >= ALL (SELECT price FROM printer)

/*3*/
SELECT *
FROM laptop
WHERE speed <= ALL (SELECT speed FROM laptop)

/*4*/
SELECT MODEL,PRICE
FROM  (SELECT MODEL,PRICE
FROM PRINTER
WHERE PRICE >= ALL(SELECT PRICE FROM PRINTER)
union
SELECT MODEL,PRICE
FROM PC
WHERE PRICE >= ALL(SELECT PRICE FROM PC)
union
SELECT MODEL,PRICE
FROM LAPTOP
WHERE PRICE >= ALL(SELECT PRICE FROM LAPTOP)) t
WHERE t. PRICE >= ALL (SELECT PRICE FROM
(SELECT MODEL,PRICE
FROM PRINTER
WHERE PRICE >= ALL(SELECT PRICE FROM PRINTER)
union
SELECT MODEL,PRICE
FROM PC
WHERE PRICE >= ALL(SELECT PRICE FROM PC)
union
SELECT MODEL, PRICE
FROM LAPTOP
WHERE PRICE >= ALL(SELECT PRICE FROM LAPTOP)) t);

/*5*/
SELECT maker
FROM product
WHERE model IN (SELECT model FROM printer WHERE color = 'y' AND price <= ALL 
					(SELECT price FROM printer WHERE color = 'y'))
/*6*/
SELECT maker
FROM product
WHERE model IN (SELECT model FROM pc p WHERE ram <= ALL
					(SELECT ram FROM pc) AND speed >= ALL (SELECT speed FROM pc WHERE ram = p.ram))
